version: "2"

services:
  redis-master:
    image: "redis:3.0-alpine"

  redis-sentinel:
    build: ./contrib
    container_name: redis-sentinel
    depends_on:
      - redis-master
    links:
      - redis-master

  postgres:
    image: "postgres:9.6-alpine"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pybossa
      - POSTGRES_PASSWORD=supersecretpassword

  # TODO: create a separate scheduler process??
  #       command: rqscheduler --host redis-master
  # background worker process
  pybossa-bgworker:
    build: .
    volumes:
      - .:/opt/pybossa
    container_name: pybossa-bgworker
    environment:
      - POSTGRES_URL=postgresql://pybossa:supersecretpassword@postgres/pybossa
    links:
      - redis-master
      - redis-sentinel
    command: python app_context_rqworker.py scheduled_jobs super high medium low email maintenance

  # web server
  # Put this in /etc/docker/daemon.json:
  # {                                                                     
  #     "dns": ["YOUR_DNS_IP_HERE", "YOUR_DNS_IP_HERE"]   
  # }
  # Now restart docker:
  # sudo service docker restart
  pybossa:
    build: .
    volumes:
      - .:/opt/pybossa
    container_name: pybossa
    environment:
      - POSTGRES_URL=postgresql://pybossa:supersecretpassword@postgres/pybossa
    links:
      - redis-master
      - redis-sentinel
    ports:
      - "5000:5000"
    command: bash -c "FLASK_APP=run.py FLASK_DEBUG=1 python -m flask run --host=0.0.0.0"
